# Your Solution

version: "3"
services:
  book-catalog:
    image: book-catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL= postgresql://akashtask8_user:9SE6dI6MxAJYa0hP04h0B0LYO34zZyzQ@dpg-crrvk2rtq21c73da64r0-a.oregon-postgres.render.com/akashtask8

  inventory-management:
    image: inventory-management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL= postgresql://akashtask8_user:9SE6dI6MxAJYa0hP04h0B0LYO34zZyzQ@dpg-crrvk2rtq21c73da64r0-a.oregon-postgres.render.com/akashtask8